name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: extractions/setup-just@v2

      - name: Test
        run: just test

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v4
        with:
          files: coverage.out
          fail_ci_if_error: true
          token: ${{ secrets.CODECOV_TOKEN }}
